/** Pasted into a coding agent to set the project up from scratch. */
export const installPrompt = [
  "Set up the mai-tan-app B2B SaaS starter kit for local development on this machine, end to end,",
  "and stop to ask me only if a step genuinely cannot be completed without a decision from me.",
  "",
  "1. Check the prerequisites and report their versions: Node.js 22.22.2 or newer, pnpm 11 or newer,",
  "   and Docker with the Compose v2 plugin. If pnpm is missing, run `corepack enable pnpm`. If Node",
  "   is too old or Docker is unavailable, stop and tell me what to install.",
  "2. Confirm ports 3000 and 5432 are free. If either is taken, tell me what is holding it and stop",
  "   rather than killing the process yourself.",
  "3. If the repository is not already in the current directory, clone",
  "   https://github.com/g-mai/mai-tan-app and cd into it. Then run `pnpm install`.",
  "4. Create `.env` from `.env.example`, which already carries working local defaults, and generate a",
  "   real session secret in the same step:",
  '   cp .env.example .env && perl -pi -e "s|^BETTER_AUTH_SECRET=.*|BETTER_AUTH_SECRET=$(openssl rand -base64 32)|" .env',
  "   Leave every other value as it is: the Resend and R2 entries are deliberate placeholders, and",
  "   `src/lib/env.ts` parses the environment with Zod at import time and rejects empty values, so do",
  "   not blank any of them out. Never invent credentials that look real, and never put secrets of",
  "   mine in the file unless I give them to you. Leave `.env` untracked; do not commit it or any",
  "   other file.",
  "5. Start PostgreSQL with `docker compose up -d` and wait until the container reports healthy.",
  "6. Run `pnpm db:migrate` to create the schema, then `pnpm db:seed` to load demo users,",
  "   organizations and teams.",
  "7. Start the dev server with `pnpm dev` in the background, wait for it to be ready, and verify that",
  "   http://localhost:3000 responds and that the server log shows no environment or database errors.",
  "8. Verify the toolchain is healthy: `pnpm check` (Biome) and `pnpm test` (Vitest) should pass.",
  "9. Report back: the versions you found, the file you created, the URL to open, and the seeded login",
  "   credentials taken from `src/lib/db/seed-data.ts` (for example gordon.freeman@blackmesa.com with",
  "   password Crowbar123). Mention that registering a brand-new account requires a real Resend API",
  "   key, because sign-up sends a 6-digit OTP by email and the code is never logged, so I should sign",
  "   in with a seeded account until I add one.",
  "",
  "If a command fails, show me the actual error output and your diagnosis before trying a fix, and do",
  "not modify application source files to work around setup problems.",
].join("\n");
