/** Pasted into a coding agent to set the project up from scratch. */
export const installPrompt = [
  "Set up the mai-tan-app B2B SaaS starter kit for local development on this machine, end to end,",
  "and stop to ask me only if a step genuinely cannot be completed without a decision from me.",
  "",
  "1. Check the prerequisites and report their versions: Node.js 22.22.2 or newer and pnpm 11 or",
  "   newer. If pnpm is missing, run `corepack enable pnpm`. If Node is too old, stop and tell me",
  "   what to install. There is no database server to set up: D1 runs locally inside Miniflare,",
  "   which `pnpm dev` starts for you.",
  "2. Confirm port 3000 is free. If it is taken, tell me what is holding it and stop rather than",
  "   killing the process yourself.",
  "3. If the repository is not already in the current directory, clone",
  "   https://github.com/g-mai/mai-tan-app and cd into it. Then run `pnpm install`.",
  "4. Create the two environment files from their templates, generating a real session secret in the",
  "   same step:",
  "   cp .env.example .env",
  '   cp .dev.vars.example .dev.vars && perl -pi -e "s|^BETTER_AUTH_SECRET=.*|BETTER_AUTH_SECRET=$(openssl rand -base64 32)|" .dev.vars',
  "   Leave the optional Resend, R2, Cloudflare, and Sentry entries blank until those integrations",
  "   are used. Never invent credentials that look real, and never put secrets of",
  "   mine in the file unless I give them to you. Leave `.env` and `.dev.vars` untracked; do not",
  "   commit them or any other file.",
  "5. Run `pnpm db:migrate:local` to create the schema in the local D1 database.",
  "6. Start the dev server with `pnpm dev` in the background, wait for it to be ready, and verify that",
  "   http://localhost:3000 responds and that the server log shows no environment or database errors.",
  "7. Verify the toolchain is healthy: `pnpm check` (Biome) and `pnpm test` (Vitest) should pass.",
  "8. Report back: the versions you found, the files you created, and the URL to open. Tell me that",
  "   registering an account requires a real Resend API key, because sign-up sends a 6-digit OTP by",
  "   email and the code is never logged, so I should put a real key in `RESEND_API_KEY` and set",
  "   `FROM_ADDRESS_EMAIL` to onboarding@resend.dev before trying to sign up.",
  "",
  "If a command fails, show me the actual error output and your diagnosis before trying a fix, and do",
  "not modify application source files to work around setup problems.",
].join("\n");
