/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ProtectedTeamsIndexRouteImport } from './routes/_protected/teams/index'
import { Route as ProtectedStackIndexRouteImport } from './routes/_protected/stack/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedOrganizationsIndexRouteImport } from './routes/_protected/organizations/index'
import { Route as ProtectedDocsIndexRouteImport } from './routes/_protected/docs/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedTeamsNewRouteImport } from './routes/_protected/teams/new'
import { Route as ProtectedTeamsTeamIdRouteImport } from './routes/_protected/teams/$teamId'
import { Route as ProtectedStackTanstackStartRouteImport } from './routes/_protected/stack/tanstack-start'
import { Route as ProtectedStackDrizzleOrmRouteImport } from './routes/_protected/stack/drizzle-orm'
import { Route as ProtectedStackBetterAuthRouteImport } from './routes/_protected/stack/better-auth'
import { Route as ProtectedSettingsBillingRouteImport } from './routes/_protected/settings/billing'
import { Route as ProtectedOrganizationsNewRouteImport } from './routes/_protected/organizations/new'
import { Route as ProtectedOrganizationsOrgIdRouteImport } from './routes/_protected/organizations/$orgId'
import { Route as ProtectedDocsGetStartedRouteImport } from './routes/_protected/docs/get-started'
import { Route as ProtectedDocsChangelogRouteImport } from './routes/_protected/docs/changelog'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedTeamsIndexRoute = ProtectedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStackIndexRoute = ProtectedStackIndexRouteImport.update({
  id: '/stack/',
  path: '/stack/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrganizationsIndexRoute =
  ProtectedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDocsIndexRoute = ProtectedDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTeamsNewRoute = ProtectedTeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTeamsTeamIdRoute = ProtectedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStackTanstackStartRoute =
  ProtectedStackTanstackStartRouteImport.update({
    id: '/stack/tanstack-start',
    path: '/stack/tanstack-start',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStackDrizzleOrmRoute =
  ProtectedStackDrizzleOrmRouteImport.update({
    id: '/stack/drizzle-orm',
    path: '/stack/drizzle-orm',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStackBetterAuthRoute =
  ProtectedStackBetterAuthRouteImport.update({
    id: '/stack/better-auth',
    path: '/stack/better-auth',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSettingsBillingRoute =
  ProtectedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationsNewRoute =
  ProtectedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationsOrgIdRoute =
  ProtectedOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDocsGetStartedRoute = ProtectedDocsGetStartedRouteImport.update({
  id: '/docs/get-started',
  path: '/docs/get-started',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDocsChangelogRoute = ProtectedDocsChangelogRouteImport.update({
  id: '/docs/changelog',
  path: '/docs/changelog',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/docs/changelog': typeof ProtectedDocsChangelogRoute
  '/docs/get-started': typeof ProtectedDocsGetStartedRoute
  '/organizations/$orgId': typeof ProtectedOrganizationsOrgIdRoute
  '/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/stack/better-auth': typeof ProtectedStackBetterAuthRoute
  '/stack/drizzle-orm': typeof ProtectedStackDrizzleOrmRoute
  '/stack/tanstack-start': typeof ProtectedStackTanstackStartRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/': typeof ProtectedDocsIndexRoute
  '/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/stack/': typeof ProtectedStackIndexRoute
  '/teams/': typeof ProtectedTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/docs/changelog': typeof ProtectedDocsChangelogRoute
  '/docs/get-started': typeof ProtectedDocsGetStartedRoute
  '/organizations/$orgId': typeof ProtectedOrganizationsOrgIdRoute
  '/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/stack/better-auth': typeof ProtectedStackBetterAuthRoute
  '/stack/drizzle-orm': typeof ProtectedStackDrizzleOrmRoute
  '/stack/tanstack-start': typeof ProtectedStackTanstackStartRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs': typeof ProtectedDocsIndexRoute
  '/organizations': typeof ProtectedOrganizationsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/stack': typeof ProtectedStackIndexRoute
  '/teams': typeof ProtectedTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/docs/changelog': typeof ProtectedDocsChangelogRoute
  '/_protected/docs/get-started': typeof ProtectedDocsGetStartedRoute
  '/_protected/organizations/$orgId': typeof ProtectedOrganizationsOrgIdRoute
  '/_protected/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/_protected/settings/billing': typeof ProtectedSettingsBillingRoute
  '/_protected/stack/better-auth': typeof ProtectedStackBetterAuthRoute
  '/_protected/stack/drizzle-orm': typeof ProtectedStackDrizzleOrmRoute
  '/_protected/stack/tanstack-start': typeof ProtectedStackTanstackStartRoute
  '/_protected/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/_protected/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/docs/': typeof ProtectedDocsIndexRoute
  '/_protected/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/stack/': typeof ProtectedStackIndexRoute
  '/_protected/teams/': typeof ProtectedTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/docs/changelog'
    | '/docs/get-started'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/settings/billing'
    | '/stack/better-auth'
    | '/stack/drizzle-orm'
    | '/stack/tanstack-start'
    | '/teams/$teamId'
    | '/teams/new'
    | '/api/auth/$'
    | '/docs/'
    | '/organizations/'
    | '/settings/'
    | '/stack/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/docs/changelog'
    | '/docs/get-started'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/settings/billing'
    | '/stack/better-auth'
    | '/stack/drizzle-orm'
    | '/stack/tanstack-start'
    | '/teams/$teamId'
    | '/teams/new'
    | '/api/auth/$'
    | '/docs'
    | '/organizations'
    | '/settings'
    | '/stack'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_protected/dashboard'
    | '/_protected/docs/changelog'
    | '/_protected/docs/get-started'
    | '/_protected/organizations/$orgId'
    | '/_protected/organizations/new'
    | '/_protected/settings/billing'
    | '/_protected/stack/better-auth'
    | '/_protected/stack/drizzle-orm'
    | '/_protected/stack/tanstack-start'
    | '/_protected/teams/$teamId'
    | '/_protected/teams/new'
    | '/api/auth/$'
    | '/_protected/docs/'
    | '/_protected/organizations/'
    | '/_protected/settings/'
    | '/_protected/stack/'
    | '/_protected/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/teams/': {
      id: '/_protected/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof ProtectedTeamsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stack/': {
      id: '/_protected/stack/'
      path: '/stack'
      fullPath: '/stack/'
      preLoaderRoute: typeof ProtectedStackIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/organizations/': {
      id: '/_protected/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof ProtectedOrganizationsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/docs/': {
      id: '/_protected/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof ProtectedDocsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/teams/new': {
      id: '/_protected/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof ProtectedTeamsNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/teams/$teamId': {
      id: '/_protected/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof ProtectedTeamsTeamIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stack/tanstack-start': {
      id: '/_protected/stack/tanstack-start'
      path: '/stack/tanstack-start'
      fullPath: '/stack/tanstack-start'
      preLoaderRoute: typeof ProtectedStackTanstackStartRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stack/drizzle-orm': {
      id: '/_protected/stack/drizzle-orm'
      path: '/stack/drizzle-orm'
      fullPath: '/stack/drizzle-orm'
      preLoaderRoute: typeof ProtectedStackDrizzleOrmRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stack/better-auth': {
      id: '/_protected/stack/better-auth'
      path: '/stack/better-auth'
      fullPath: '/stack/better-auth'
      preLoaderRoute: typeof ProtectedStackBetterAuthRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/billing': {
      id: '/_protected/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof ProtectedSettingsBillingRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/organizations/new': {
      id: '/_protected/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof ProtectedOrganizationsNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/organizations/$orgId': {
      id: '/_protected/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof ProtectedOrganizationsOrgIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/docs/get-started': {
      id: '/_protected/docs/get-started'
      path: '/docs/get-started'
      fullPath: '/docs/get-started'
      preLoaderRoute: typeof ProtectedDocsGetStartedRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/docs/changelog': {
      id: '/_protected/docs/changelog'
      path: '/docs/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof ProtectedDocsChangelogRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDocsChangelogRoute: typeof ProtectedDocsChangelogRoute
  ProtectedDocsGetStartedRoute: typeof ProtectedDocsGetStartedRoute
  ProtectedOrganizationsOrgIdRoute: typeof ProtectedOrganizationsOrgIdRoute
  ProtectedOrganizationsNewRoute: typeof ProtectedOrganizationsNewRoute
  ProtectedSettingsBillingRoute: typeof ProtectedSettingsBillingRoute
  ProtectedStackBetterAuthRoute: typeof ProtectedStackBetterAuthRoute
  ProtectedStackDrizzleOrmRoute: typeof ProtectedStackDrizzleOrmRoute
  ProtectedStackTanstackStartRoute: typeof ProtectedStackTanstackStartRoute
  ProtectedTeamsTeamIdRoute: typeof ProtectedTeamsTeamIdRoute
  ProtectedTeamsNewRoute: typeof ProtectedTeamsNewRoute
  ProtectedDocsIndexRoute: typeof ProtectedDocsIndexRoute
  ProtectedOrganizationsIndexRoute: typeof ProtectedOrganizationsIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedStackIndexRoute: typeof ProtectedStackIndexRoute
  ProtectedTeamsIndexRoute: typeof ProtectedTeamsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDocsChangelogRoute: ProtectedDocsChangelogRoute,
  ProtectedDocsGetStartedRoute: ProtectedDocsGetStartedRoute,
  ProtectedOrganizationsOrgIdRoute: ProtectedOrganizationsOrgIdRoute,
  ProtectedOrganizationsNewRoute: ProtectedOrganizationsNewRoute,
  ProtectedSettingsBillingRoute: ProtectedSettingsBillingRoute,
  ProtectedStackBetterAuthRoute: ProtectedStackBetterAuthRoute,
  ProtectedStackDrizzleOrmRoute: ProtectedStackDrizzleOrmRoute,
  ProtectedStackTanstackStartRoute: ProtectedStackTanstackStartRoute,
  ProtectedTeamsTeamIdRoute: ProtectedTeamsTeamIdRoute,
  ProtectedTeamsNewRoute: ProtectedTeamsNewRoute,
  ProtectedDocsIndexRoute: ProtectedDocsIndexRoute,
  ProtectedOrganizationsIndexRoute: ProtectedOrganizationsIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedStackIndexRoute: ProtectedStackIndexRoute,
  ProtectedTeamsIndexRoute: ProtectedTeamsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
