/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoR2RouteImport } from './routes/demo/r2'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedAuthenticatedRouteImport } from './routes/_protected/authenticated'
import { Route as ProtectedAboutRouteImport } from './routes/_protected/about'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ProtectedTeamsIndexRouteImport } from './routes/_protected/teams/index'
import { Route as ProtectedOrganizationsIndexRouteImport } from './routes/_protected/organizations/index'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedTeamsNewRouteImport } from './routes/_protected/teams/new'
import { Route as ProtectedTeamsTeamIdRouteImport } from './routes/_protected/teams/$teamId'
import { Route as ProtectedOrganizationsNewRouteImport } from './routes/_protected/organizations/new'
import { Route as ProtectedOrganizationsOrgIdRouteImport } from './routes/_protected/organizations/$orgId'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoR2Route = DemoR2RouteImport.update({
  id: '/demo/r2',
  path: '/demo/r2',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAuthenticatedRoute = ProtectedAuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAboutRoute = ProtectedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedTeamsIndexRoute = ProtectedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrganizationsIndexRoute =
  ProtectedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTeamsNewRoute = ProtectedTeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTeamsTeamIdRoute = ProtectedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrganizationsNewRoute =
  ProtectedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationsOrgIdRoute =
  ProtectedOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/about': typeof ProtectedAboutRoute
  '/authenticated': typeof ProtectedAuthenticatedRoute
  '/settings': typeof ProtectedSettingsRoute
  '/demo/r2': typeof DemoR2Route
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/organizations/$orgId': typeof ProtectedOrganizationsOrgIdRoute
  '/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/teams/': typeof ProtectedTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/about': typeof ProtectedAboutRoute
  '/authenticated': typeof ProtectedAuthenticatedRoute
  '/settings': typeof ProtectedSettingsRoute
  '/demo/r2': typeof DemoR2Route
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/organizations/$orgId': typeof ProtectedOrganizationsOrgIdRoute
  '/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/organizations': typeof ProtectedOrganizationsIndexRoute
  '/teams': typeof ProtectedTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_protected/about': typeof ProtectedAboutRoute
  '/_protected/authenticated': typeof ProtectedAuthenticatedRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/demo/r2': typeof DemoR2Route
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/organizations/$orgId': typeof ProtectedOrganizationsOrgIdRoute
  '/_protected/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/_protected/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/_protected/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/_protected/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/_protected/teams/': typeof ProtectedTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/authenticated'
    | '/settings'
    | '/demo/r2'
    | '/demo/tanstack-query'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/api/auth/$'
    | '/demo/sentry/testing'
    | '/organizations/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/authenticated'
    | '/settings'
    | '/demo/r2'
    | '/demo/tanstack-query'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/api/auth/$'
    | '/demo/sentry/testing'
    | '/organizations'
    | '/teams'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_protected/about'
    | '/_protected/authenticated'
    | '/_protected/settings'
    | '/demo/r2'
    | '/demo/tanstack-query'
    | '/_protected/'
    | '/_protected/organizations/$orgId'
    | '/_protected/organizations/new'
    | '/_protected/teams/$teamId'
    | '/_protected/teams/new'
    | '/api/auth/$'
    | '/demo/sentry/testing'
    | '/_protected/organizations/'
    | '/_protected/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  DemoR2Route: typeof DemoR2Route
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/r2': {
      id: '/demo/r2'
      path: '/demo/r2'
      fullPath: '/demo/r2'
      preLoaderRoute: typeof DemoR2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/authenticated': {
      id: '/_protected/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof ProtectedAuthenticatedRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/about': {
      id: '/_protected/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ProtectedAboutRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/teams/': {
      id: '/_protected/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof ProtectedTeamsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/organizations/': {
      id: '/_protected/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof ProtectedOrganizationsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/teams/new': {
      id: '/_protected/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof ProtectedTeamsNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/teams/$teamId': {
      id: '/_protected/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof ProtectedTeamsTeamIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/organizations/new': {
      id: '/_protected/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof ProtectedOrganizationsNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/organizations/$orgId': {
      id: '/_protected/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof ProtectedOrganizationsOrgIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedAboutRoute: typeof ProtectedAboutRoute
  ProtectedAuthenticatedRoute: typeof ProtectedAuthenticatedRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedOrganizationsOrgIdRoute: typeof ProtectedOrganizationsOrgIdRoute
  ProtectedOrganizationsNewRoute: typeof ProtectedOrganizationsNewRoute
  ProtectedTeamsTeamIdRoute: typeof ProtectedTeamsTeamIdRoute
  ProtectedTeamsNewRoute: typeof ProtectedTeamsNewRoute
  ProtectedOrganizationsIndexRoute: typeof ProtectedOrganizationsIndexRoute
  ProtectedTeamsIndexRoute: typeof ProtectedTeamsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAboutRoute: ProtectedAboutRoute,
  ProtectedAuthenticatedRoute: ProtectedAuthenticatedRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedOrganizationsOrgIdRoute: ProtectedOrganizationsOrgIdRoute,
  ProtectedOrganizationsNewRoute: ProtectedOrganizationsNewRoute,
  ProtectedTeamsTeamIdRoute: ProtectedTeamsTeamIdRoute,
  ProtectedTeamsNewRoute: ProtectedTeamsNewRoute,
  ProtectedOrganizationsIndexRoute: ProtectedOrganizationsIndexRoute,
  ProtectedTeamsIndexRoute: ProtectedTeamsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  DemoR2Route: DemoR2Route,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
